CHINESE_TEXT = {
	BIOME_TEXT:{
		'Kerbol':'太阳',
		'North Pole':'北极',
		'Northern Sinkhole Ridge':'北方天坑山脊',
		'Northern Sinkhole':'北方天坑',
		'Highlands':'高原',
		'Midlands':'内陆',
		'Minor Craters':'小环形山',
		'Central Lowlands':'中央低地',
		'Western Lowlands':'西方低地',
		'South Western Lowlands':'西南低地',
		'South Eastern Lowlands':'东南低地',
		'Canyon':'峡谷',
		'South Pole':'南极',
		'Poles':'极地',
		'Lowlands':'低地',
		'Foothills':'山麓',
		'Peaks':'山顶',
		'Impact Ejecta':'撞击喷出物',
		'Explodium Sea':'硝苷之海',
		'Akatsuki Lake':'晓之湖',
		'Shallows':'浅滩',
		'Crater Lake':'陨坑湖',
		'Western Sea':'西海',
		'Olympus':'奥林匹斯山',
		'Craters':'环形山',
		'Eastern Sea':'东海',
		'Ice Caps':'冰冠',
		'Northern Ice Shelf':'北方冰架',
		'Southern Ice Shelf':'南方冰架',
		'Tundra':'冻原',
		'Mountains':'山脉',
		'Grasslands':'草原',
		'Deserts':'沙漠',
		'Badlands':'荒野',
		'Shores':'海岸',
		'Water':'水中',
		'KSC':'坎巴拉航天中心',
		'Administration':'行政中心',
		'Astronaut Complex':'宇航员之家',
		'Crawlerway':'低速车道',
		'Flag Pole':'旗杆',
		'LaunchPad':'发射台',
		'Mission Control':'任务控制中心',
		'R&D':'科研中心',
		'R&D Central Building':'科研中心主楼',
		'R&D Corner Lab':'科研中心角落研究室',
		'R&D Main Building':'科研中心主要建筑物',
		'R&D Observatory':'科研中心天文台',
		'R&D Side Lab':'科研中心侧面研究室',
		'R&D Small Lab':'科研中心小研究室',
		'R&D Tanks':'科研中心燃料罐阵列',
		'R&D Wind Tunnel':'科研中心风洞设备',
		'Runway':'跑道',
		'SPH':'空天飞机库(SPH)',
		'SPH Main Building':'SPH主建筑',
		'SPH Round Tank':'SPH圆形燃料罐',
		'SPH Tanks':'SPH燃料罐阵列',
		'SPH Water Tower':'SPH水塔',
		'Tracking Station':'跟踪站',
		'Tracking Station Dish East':'跟踪站东部天线',
		'Tracking Station Dish North':'跟踪站北部天线',
		'Tracking Station Dish South':'跟踪站南部天线',
		'Tracking Station Hub':'跟踪站本部',
		'VAB':'火箭组装大楼(VAB)',
		'VAB Main Building':'VAB主建筑',
		'VAB Pod Memorial':'VAB指令舱纪念碑',
		'VAB Round Tank':'VAB圆形燃料罐',
		'VAB South Complex':'VAB南部设施',
		'VAB Tanks':'VAB燃料罐阵列',
		'Polar Lowlands':'极地低地',
		'Polar Crater':'极地环形山',
		'Highland Craters':'高原环形山',
		'Midland Craters':'内陆环形山',
		'Northern Basin':'北方盆地',
		'Farside Basin':'远方盆地',
		'Northwest Crater':'西北环形山',
		'East Farside Crater':'远东环形山',
		'Canyons':'大峡谷',
		'Farside Crater':'远方撞击坑',
		'East Crater':'东方环形山',
		'Twin Craters':'双子撞击坑',
		'Southwest Crater':'西南环形山',
		'Slopes':'山坡',
		'Flats':'平原',
		'Lesser Flats':'小平原',
		'Great Flats':'大平原',
		'Greater Flats':'超大平原',
		'Polar Highlands':'极地高地',
		'Polar Craters':'极地环形山群',
		'Midland Sea':'内陆海',
		'Southern Basin':'南方盆地',
		'Northern Shelf':'北方浅滩',
		'Midland Canyon':'内陆峡谷',
		'Eastern Canyon':'东方峡谷',
		'Western Canyon':'西方峡谷',
		'Eastern Mountain Ridge':'东方山脉',
		'Western Mountain Ridge':'西方山脉',
		'Central Mountain Range':'中央山脉',
		'South Eastern Mountain Range':'东南山脉',
		'Ridges':'山脊',
		'Impact Craters':'撞击坑洞区',
		'Dunes':'沙丘',
		'Crescent Bay':'新月湾',
		'The Sagen Sea':'萨根海',
		'Crater Island':'陨坑岛',
		'Crater Bay':'陨坑湾',
		'DeGrasse Sea':'德格拉斯海',
		'Northeast Basin':'东北盆地',
		'Northwest Basin':'西北盆地',
		'Southern Valleys':'南方峡谷',
		'Mara':'玛拉',
		'Gagarin Crater':'加加林环形山',
		'Grissom Crater':'格里索姆环形山',
		'Galileio Crater':'伽利略环形山',
		'Tycho Crater':'第谷撞击坑',
		'Valley':'山谷',
		'Northern Glaciers':'北方冰川',
		'Ice Canyons':'冰冻峡谷',
		'Fragipan':'脆磐层',
		'Babbage Patch':'巴贝奇的斑点',
		'Southern Glaciers':'南方冰川',
		'Mu Glacier':'姆冰川'
	},
	INSTRUMENT_TEXT:{
		'Crew Report':'乘员报告',
		'EVA Report':'EVA报告',
		'Gravity Scan':'重力扫描',
		'Mystery Goo Observation':'mysteryGoo',
		'Seismic Scan':'神秘黏性物质™观察结果',
		'Surface Sample':'地表样本',
		'Materials Study':'材料研究',
		'Atmospheric Pressure Scan': '大气压扫描',
		'Temperature Scan':'温度扫描',
		'Atmosphere Analysis':'大气分析',
		'Infrared Telescope':'红外望远镜',
		'recovery':'载具回收'
	},
	LOCATION_TEXT:{
		'In Space High':'较远的太空中',
		'In Space Low':'较近的太空中',
		'Flying High':'高层大气中',
		'Flying Low':'飞越',
		'Surface: Landed':'地面',
		'Surface: Splashed':'水面',
		'Flyby':'太空飞过',
		'Orbital Flight':'轨道',
		'Suborbital Flight':'亚轨道',
		'Atmospheric Flight':'大气飞行',
		'Surface Landed':'登陆',
	},
}
